GRAD2-2853: initial implementation of student course CRUD is committed.
bcgov/EDUC-GRAD-COURSE-API pull request #310
Opened 2024-07-15 21:29 UTC by infstar

GRAD2-2853: initial implementation of student course CRUD is committed.

2024-07-18 21:49 UTC, cditcher requested changes

2024-07-18 21:49 UTC, cditcher commented on api/src/main/java/ca/bc/gov/educ/api/course/controller/v2/CourseController.java
> +    private static final String BEARER = "Bearer ";
Don't need BEARER now

2024-07-18 21:49 UTC, cditcher commented on api/src/main/java/ca/bc/gov/educ/api/course/controller/v2/StudentCourseController.java
> +    private static final String BEARER = "Bearer ";
Remove BEARER

2024-08-08 21:40 UTC, infstar commented on api/src/main/java/ca/bc/gov/educ/api/course/controller/v2/StudentCourseController.java
> +    @ApiResponses(value = {@ApiResponse(responseCode = "200", description = "OK"),
This one is also updating as well if it already exists.

2024-08-08 21:45 UTC, infstar commented on api/src/main/java/ca/bc/gov/educ/api/course/controller/v2/StudentCourseController.java
> +            return new ResponseEntity<>(HttpStatus.BAD_REQUEST);
Inside "stopOnErrors()",  it throws GradBusinessRuleException, so the line 56 seems not reachable.

2024-08-08 21:49 UTC, infstar commented on api/src/main/java/ca/bc/gov/educ/api/course/controller/v2/StudentCourseController.java
> +    }
saveStudentCourse method is for create & update.

2024-08-08 21:51 UTC, infstar commented on api/src/main/java/ca/bc/gov/educ/api/course/controller/v2/StudentCourseController.java
> +            return new ResponseEntity<>(HttpStatus.BAD_REQUEST);
which means validation error returns with 422.

2024-08-08 21:54 UTC, infstar commented on api/src/main/java/ca/bc/gov/educ/api/course/controller/v2/CourseController.java
> +    @ApiResponses(value = {@ApiResponse(responseCode = "200", description = "OK")})
done

2024-08-08 21:55 UTC, infstar commented on api/src/main/java/ca/bc/gov/educ/api/course/controller/v2/CourseController.java
> +    @ApiResponses(value = {@ApiResponse(responseCode = "200", description = "OK")})
done

2024-08-08 21:55 UTC, infstar commented on api/src/main/java/ca/bc/gov/educ/api/course/controller/v2/StudentCourseController.java
> +    private static final String BEARER = "Bearer ";
removed.

2024-08-09 15:32 UTC, cditcher commented on api/src/main/java/ca/bc/gov/educ/api/course/controller/v2/StudentCourseController.java
> +    @ApiResponses(value = {@ApiResponse(responseCode = "200", description = "OK"),
Need a separate endpoint for updates that uses PUT. We should not combine functionality on REST endpoints it breaks REST contract.

2024-08-27 15:26 UTC, cditcher requested changes

2024-08-27 15:26 UTC, cditcher commented on api/src/main/java/ca/bc/gov/educ/api/course/controller/v2/CourseController.java
> +        log.info("#getCourseDetails : courseID={}", courseID);
Change to debug level

2024-08-27 15:26 UTC, cditcher commented on api/src/main/java/ca/bc/gov/educ/api/course/controller/v2/CourseController.java
> +        log.info("#getCourseDetails : courseCode={}, courseLevel={}", courseCode, courseLevel);
debug

2024-08-27 15:26 UTC, cditcher commented on api/src/main/java/ca/bc/gov/educ/api/course/controller/v2/StudentCourseController.java
> +            @ApiResponse(responseCode = "422", description = "VALIDATION ERROR")
Validation errors should be 400 as per https://www.rfc-editor.org/rfc/rfc7231#section-6.5.1

2024-08-27 15:26 UTC, cditcher commented on api/src/main/java/ca/bc/gov/educ/api/course/controller/v2/StudentCourseController.java
> +    @ApiResponses(value = {@ApiResponse(responseCode = "200", description = "OK"),
Validation errors should be 400 as per https://www.rfc-editor.org/rfc/rfc7231#section-6.5.1

2024-08-27 16:40 UTC, infstar commented on api/src/main/java/ca/bc/gov/educ/api/course/controller/v2/CourseController.java
> +        log.info("#getCourseDetails : courseID={}", courseID);
done

2024-08-27 16:41 UTC, infstar commented on api/src/main/java/ca/bc/gov/educ/api/course/controller/v2/StudentCourseController.java
> +            @ApiResponse(responseCode = "422", description = "VALIDATION ERROR")
description is updated.

2024-08-27 17:23 UTC, cditcher approved these changes

2024-08-27 21:10 UTC, merged